basePath: /api/v1
definitions:
  main.User:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: John Doe
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: This is a sample server for demonstrating Swagger in Go using Gin.
  title: Go Swagger Example API
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
        - application/json
      description: Get account by ID
      parameters:
        - description: Account ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/main.Account"
        "400":
          description: Bad request
          schema:
            type: string
      summary: Get an account by ID
      tags:
        - users
swagger: "2.0"
